apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: mysql-root-pass
  literals:
  - password=redacted
- name: wp-db-host
  literals:
    - host=redacted
- name: wp-db-user
  literals:
    - password=redacted
- name: mysql-db-pass
  literals:
    - password=redacted
- name: wp-db-name
  literals:
    - password=redacted
resources:
  # Enable/uncomment if using RPI or any other setup then public cloud
  - metallb-ingress-service.yaml
  # Enable/uncomment if using nfs-server-k8s on public or private cloud
  #- nfs.yaml
  # Enable/uncomment if using RPI or any other setup then public cloud
  - nfs-synology.yaml
  # Enable/uncomment if you want to deploy MySQL cluster using MySQL operator on private or public cloud
  #- mysql-cluster.yaml
  # Leave enabled/uncommented for both private and public cloud
  - wordpress-deployment.yaml
  # Enable/uncomment on private cloud if "Step 7.2" of https://foolcontrol.org/?p=4004 has been completed
  - vpa.yaml
  - hpa.yaml
  # Enable/uncomment if using public cloud or if you using inlets-operator on private cloud/RPI
  #- ingress.yaml

# References:
# wp-k8s: WordPress on privately hosted Kubernetes cluster (Raspberry Pi 4 + Synology): https://foolcontrol.org/?p=4004
# wp-k8s: WordPress on Kubernetes project (GKE, cloud SQL, NFS, cluster autoscaling, HPA, VPA, Ingress, Let’s Encrypt): https://foolcontrol.org/?p=3754
# nfs-server-k8s: NFS server container image for Kubernetes: https://github.com/AdnanHodzic/nfs-server-k8s
